Herover/itu-devops-h

minitwit.py, minitwit_tests.py
Consider if bytes are actually better than strings? Should we change the app to take strings?
=> Fix testfile

minitwit.py
Python 3 changes to print
Change flask to read as text instead of default binary
Change werkzeug import
=> Fix python2 -> python3, update libraries

minitwit/pom.xml, minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/register.vm
Closes #17 
Adds [Spring Security Core](https://mvnrepository.com/artifact/org.springframework.security/spring-security-core) as a dependency for easy password hashing with BCrypt.
=> Register user

docker-compose.yml, minitwit/Dockerfile, minitwit/Dockerfile_build, minitwit/control.sh, minitwit/pom.xml, minitwit/src/main/java/SQLite.java
=> Add Docker stuff

minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/timeline.vm
Closes #10 , gravatar and time formater not implemented.
=> Add more timelines and fix user timeline

minitwit/src/main/java/WebApplication.java
Added support for follow and unfollow
/<username>/follow
/<username>/unfollow
=> New follow and unfollow endpoint

minitwit/pom.xml, minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/timeline.vm
=> Display user gravatar

minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/layout.vm, minitwit/src/main/resources/templates/login.vm, minitwit/src/main/resources/templates/register.vm, minitwit/src/main/resources/templates/timeline.vm
=> Add title tag values

minitwit/pom.xml, minitwit/src/main/java/WebApplication.java
* Adds a common "path" to add sim API endpoints
* Adds basic auth protection on API endpoints
* Adds gson by google dependency for easy JSON encoding
* Move code for fetching public timeline content into own method
Consider if we should just move it directly into it's own class that can work as a independent server seperate from the WebApplication class, and perhaps create a new class for all the common functions. It's pretty easy right now and I think we might get it as a task later around 29/3.
=> Add msgs api endpoint + utilities

minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/layout.vm, minitwit/src/main/resources/templates/timeline.vm
=> Add urlFor to templates

minitwit/src/main/resources/templates/timeline.vm
Closes #53 
Very small change, should be able to merge immediately.
=> Fix username not displaying on user timeline

minitwit/src/main/java/SQLite.java, minitwit/src/main/java/WebApplication.java
We forgot to close the connection most of the time, this caused #52 and made it hard to fix # 51
=> Fix database locks

minitwit/src/main/java/WebApplication.java
Uses logged in user id and moves getConnection to after case where it returns without closing unused connection.
=> Fix add message

minitwit/src/main/java/WebApplication.java
Hopefully closes #59, couldn't reproduce it anymore.
=> Close connection some places its missing

minitwit/src/main/java/WebApplication.java
=> Add register API endpoint

minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/timeline.vm
Closes #39 but currently there's still locked db issues.
=> Fix follow/unfollow/this is you button not showing

minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/layout.vm
=> Fix invisible message input on 'my timeline'

minitwit/src/main/java/WebApplication.java
Title says it all
just fixed missing todos
=> Fixed issue 60&72, following and twits work fine now

minitwit/src/main/java/WebApplication.java
=> Fxi sim register http code

minitwit/src/main/java/WebApplication.java
Prints caught errors to terminal and show simple error to user.
=> Add error catcher that logs route errors

minitwit/.drone.yml, terraform/README.md
I forgot to add signatures to the drone config, without them anyone can create a PR with a new drone config and steal all our secret tokens to github and digital ocean
=> Add signature to drone

minitwit/pom.xml, minitwit/src/main/java/Metrics/PrometheusMetrics.java, minitwit/src/main/java/Metrics/TimerStopper.java, minitwit/src/main/java/WebApplication.java, terraform/README.md, terraform/droplets.tf, terraform/files/drone/docker-compose.yml, terraform/files/install_docker.sh, terraform/files/install_node_exporter.sh, terraform/files/monitoring/docker-compose.yml, terraform/files/monitoring/prometheus.yml, terraform/files/update_image.sh, terraform/provider.tf, terraform/setup_server_drone.sh, terraform/setup_server_monitoring.sh, terraform/setup_server_web.sh
=> Monitoring

minitwit/.drone.yml, terraform/README.md, terraform/files/drone/docker-compose.yml
=> Add snyk ci-cd step

minitwit/.drone.yml, terraform/files/update_image.sh
=> Add github release step to drone and real release to prod

terraform/files/update_image.sh
Fixes wrong port number and places db in subfolder to help fix readonly problems.
=> Fix docker minitwit server run issues

SLA.md
=> Added new SLA

minitwit/.drone.yml
Until we get can get a non-vulnerble maven openjdk image.
=> Disable snyk

docker-compose.yml
=> Add postgresql database to common docker-compose

minitwit/.drone.yml
Reverts Herover/itu-devops-h#138
=> Revert "Disable snyk"

license.md, minitwit/pom.xml
Some commits haven't been merged yet, such as the license.
=> Merge dev to main

minitwit/src/main/java/WebApplication.java, minitwit/src/main/resources/templates/layout.vm, minitwit/src/main/resources/templates/timeline.vm
=> Fix XSS vuln

report/index.adoc
Adds some more ITU information and centers it all, making it look a bit nicer. Also fixes Lucas's wrong ITU initials. :P
=> Improve the look of the header (report)

minitwit/pom.xml, report/deployment_strategy.adoc, report/lesson_learned.adoc, report/logging.adoc, report/monitoring.adoc, report/security_assesment.adoc
Co-authored-by: Eren <erentomurcuk@users.noreply.github.com>
Co-authored-by: Leonora Andrea Lindqvist Nielsen <hi+git@leonora.app>
Co-authored-by: Smilla Dion <smilla.dion@live.dk>
Co-authored-by: Lucas Heede Vulpius <lucasv9@live.dk>
=> Lessons learned
